// PARTE 3: Perguntas Específicas por Idioma (PT/EN)
// PART 3: Language Specific Questions (PT/EN)
const questionsPart3 = [
    // PT Specific
    { id: "pt_301", langs: ["pt"], pt: "O Alojamento Local (Airbnb) destruiu os centros das cidades e deve ser proibido em zonas residenciais.", en: "[PT] Short-term rentals destroyed city centers and should be banned.", effect: { axis: "eco_act", weight: -1 } },
    { id: "pt_302", langs: ["pt"], pt: "Para resolver a crise da habitação, é necessário relaxar as leis ambientais e de construção.", en: "[PT] To solve housing crisis, we must relax environmental/building laws.", effect: { axis: "eco_act", weight: 1 } },
    { id: "pt_303", langs: ["pt"], pt: "O Estado deve obrigar os médicos formados no público a trabalhar no SNS durante alguns anos.", en: "[PT] State must force public-trained doctors to work in public sector for some years.", effect: { axis: "phil_soc", weight: -1 } },
    { id: "pt_304", langs: ["pt"], pt: "A semana de 4 dias de trabalho é uma utopia impossível para a economia portuguesa atual.", en: "[PT] The 4-day work week is an impossible utopia.", effect: { axis: "eco_sys", weight: 1 } },
    { id: "pt_305", langs: ["pt"], pt: "O imposto sobre os combustíveis (ISP) é excessivo e o governo usa a inflação para lucrar.", en: "[PT] Fuel tax is excessive and gov capitalizes on inflation.", effect: { axis: "gov_scope", weight: -1 } },
    { id: "pt_306", langs: ["pt"], pt: "As propinas no ensino superior público deveriam ser totalmente abolidas.", en: "[PT] Public university tuition should be abolished.", effect: { axis: "eco_sys", weight: -1 } },
    { id: "pt_307", langs: ["pt"], pt: "O Estado deve financiar colégios privados (Contratos de Associação) onde a escola pública falha.", en: "[PT] State should fund private schools where public school fails.", effect: { axis: "eco_act", weight: 1 } },
    { id: "pt_308", langs: ["pt"], pt: "A RTP (televisão pública) deve ser privatizada.", en: "[PT] Public TV (RTP) should be privatized.", effect: { axis: "eco_act", weight: 1 } },
    { id: "pt_309", langs: ["pt"], pt: "Portugal deve pedir desculpa oficial e pagar reparações às ex-colónias.", en: "[PT] Portugal should apologize and pay reparations to ex-colonies.", effect: { axis: "soc_time", weight: 1 } },
    { id: "pt_310", langs: ["pt"], pt: "O Estado Novo (regime de Salazar) teve conquistas financeiras e de segurança ignoradas hoje.", en: "[PT] The Estado Novo regime had achievements ignored today.", effect: { axis: "soc_time", weight: -1 } },
    { id: "pt_311", langs: ["pt"], pt: "A narrativa atual sobre o 25 de Abril é demasiado dominada pela esquerda política.", en: "[PT] The narrative on 25th April is too dominated by the Left.", effect: { axis: "soc_time", weight: -1 } },
    { id: "pt_312", langs: ["pt"], pt: "O 'Segredo de Justiça' serve muitas vezes para proteger os poderosos.", en: "[PT] 'Justice Secrecy' often protects the powerful.", effect: { axis: "gov_form", weight: 1 } },
    { id: "pt_313", langs: ["pt"], pt: "Os 'Mega-Processos' provam que a justiça portuguesa é incompetente e lenta.", en: "[PT] 'Mega-Processes' prove justice is incompetent.", effect: { axis: "soc_change", weight: 1 } },
    { id: "pt_314", langs: ["pt"], pt: "O número de deputados na Assembleia da República (230) devia ser reduzido drasticamente.", en: "[PT] The number of MPs should be drastically reduced.", effect: { axis: "gov_scope", weight: -1 } },
    { id: "pt_315", langs: ["pt"], pt: "O Presidente da República devia ter mais poder executivo.", en: "[PT] The President should have more executive power.", effect: { axis: "gov_form", weight: -1 } },
    { id: "pt_316", langs: ["pt"], pt: "A indústria do eucalipto é essencial para a economia e não deve ser demonizada.", en: "[PT] Eucalyptus industry is essential and shouldn't be demonized.", effect: { axis: "eco_sys", weight: 1 } },
    { id: "pt_317", langs: ["pt"], pt: "Os campos de golfe no Algarve devem ser encerrados imediatamente em períodos de seca.", en: "[PT] Golf courses in Algarve should be closed during drought.", effect: { axis: "tech_speed", weight: -1 } },
    { id: "pt_318", langs: ["pt"], pt: "As portagens nas antigas SCUT (Interior) devem ser abolidas para combater a desertificação.", en: "[PT] Interior highway tolls should be abolished.", effect: { axis: "phil_soc", weight: -1 } },
    { id: "pt_319", langs: ["pt"], pt: "Portugal tornou-se um país de 'Lisboa e o resto é paisagem'.", en: "[PT] Portugal became 'Lisbon and the rest'.", effect: { axis: "dip_moral", weight: -1 } },
    { id: "pt_320", langs: ["pt"], pt: "A decisão sobre o novo aeroporto demonstra a incapacidade da classe política.", en: "[PT] The new airport decision shows political incapacity.", effect: { axis: "soc_change", weight: 1 } },
    { id: "pt_321", langs: ["pt"], pt: "Portugal devia abandonar a aposta nas autoestradas e focar-se na ferrovia.", en: "[PT] Portugal should focus on railways instead of highways.", effect: { axis: "tech_speed", weight: -1 } },
    { id: "pt_322", langs: ["pt"], pt: "A descriminalização das drogas está a falhar e precisa de regras mais rígidas.", en: "[PT] Decriminalization of drugs is failing and needs stricter rules.", effect: { axis: "gov_scope", weight: 1 } },
    { id: "pt_323", langs: ["pt"], pt: "O Estado gasta demasiado dinheiro a apoiar eventos religiosos (JMJ).", en: "[PT] State spends too much on religious events.", effect: { axis: "soc_time", weight: 1 } },
    { id: "pt_324", langs: ["pt"], pt: "Portugal deve exigir a devolução de Olivença por parte de Espanha.", en: "[PT] Portugal must demand Olivença back from Spain.", effect: { axis: "dip_align", weight: -1 } },
    { id: "pt_325", langs: ["pt"], pt: "As 'cunhas' e o nepotismo são uma parte inevitável da cultura portuguesa.", en: "[PT] Nepotism is inevitable in Portuguese culture.", effect: { axis: "dip_moral", weight: -1 } },
    { id: "pt_326", langs: ["pt"], pt: "O turismo de massas traz mais problemas do que benefícios.", en: "[PT] Mass tourism brings more problems than benefits.", effect: { axis: "eco_act", weight: -1 } },
    { id: "pt_327", langs: ["pt"], pt: "Os sindicatos em Portugal servem mais os partidos do que os trabalhadores.", en: "[PT] Unions serve parties more than workers.", effect: { axis: "eco_act", weight: 1 } },
    { id: "pt_328", langs: ["pt"], pt: "O acordo de mobilidade da CPLP cria concorrência desleal.", en: "[PT] CPLP mobility agreement creates unfair competition.", effect: { axis: "dip_align", weight: -1 } },
    { id: "pt_329", langs: ["pt"], pt: "A ADSE é um privilégio injusto face aos trabalhadores do privado.", en: "[PT] ADSE is an unfair privilege compared to private workers.", effect: { axis: "cul_hier", weight: 1 } },
    { id: "pt_330", langs: ["pt"], pt: "Devia ser proibido plantar culturas intensivas no Alentejo devido à falta de água.", en: "[PT] Intensive crops in Alentejo should be banned due to water shortage.", effect: { axis: "tech_speed", weight: -1 } },

    // EN Specific
    { id: "en_401", langs: ["en"], pt: "[EN] A exploração de recursos deve ser controlada pelo Estado.", en: "Extraction of natural resources should be controlled by the State.", effect: { axis: "eco_sys", weight: -1 } },
    { id: "en_402", langs: ["en"], pt: "[EN] As leis devem basear-se em textos sagrados.", en: "Laws should be based on sacred texts.", effect: { axis: "soc_time", weight: -1 } },
    { id: "en_403", langs: ["en"], pt: "[EN] Filhos devem cuidar dos pais em casa, não o Estado.", en: "Children should care for elderly parents at home, not the State.", effect: { axis: "phil_soc", weight: -1 } },
    { id: "en_404", langs: ["en"], pt: "[EN] Castigo físico é legítimo em certas culturas.", en: "Physical punishment is a legitimate form of justice in certain cultures.", effect: { axis: "law_goal", weight: -1 } },
    { id: "en_405", langs: ["en"], pt: "[EN] Governo deve poder bloquear a internet.", en: "Government should have the right to block the internet.", effect: { axis: "gov_scope", weight: 1 } },
    { id: "en_406", langs: ["en"], pt: "[EN] Trabalho infantil é um mal necessário para desenvolvimento.", en: "Child labor is a necessary evil for early economic development.", effect: { axis: "eco_sys", weight: 1 } },
    { id: "en_407", langs: ["en"], pt: "[EN] Meu país tem direito a anexar territórios vizinhos.", en: "My country has the right to annex neighboring territories.", effect: { axis: "dip_align", weight: -1 } },
    { id: "en_408", langs: ["en"], pt: "[EN] Países em desenvolvimento não devem reduzir emissões.", en: "Developing countries shouldn't have to reduce emissions if it hurts growth.", effect: { axis: "tech_speed", weight: 1 } },
    { id: "en_409", langs: ["en"], pt: "[EN] Casta/Tribo deve contar para contratação.", en: "Caste/Tribe should be considered in hiring/marriage.", effect: { axis: "cul_hier", weight: -1 } },
    { id: "en_410", langs: ["en"], pt: "[EN] Governo 'mão de ferro' é melhor que democracia instável.", en: "Iron-fist government is better than unstable democracy.", effect: { axis: "gov_form", weight: -1 } },
    { id: "en_411", langs: ["en"], pt: "[EN] Estado deve expropriar terras para os pobres.", en: "State should expropriate land for the poor.", effect: { axis: "eco_sys", weight: -1 } },
    { id: "en_412", langs: ["en"], pt: "[EN] Mulheres devem ser educadas para serem esposas.", en: "Women should be educated to be good wives/mothers.", effect: { axis: "soc_time", weight: -1 } },
    { id: "en_413", langs: ["en"], pt: "[EN] Vigilância em massa é um preço justo pela segurança.", en: "Mass surveillance is a fair price for low crime.", effect: { axis: "gov_scope", weight: 1 } },
    { id: "en_414", langs: ["en"], pt: "[EN] Influência ocidental é imperialismo.", en: "Western cultural influence is imperialism.", effect: { axis: "dip_align", weight: -1 } },
    { id: "en_415", langs: ["en"], pt: "[EN] Património não deve ser taxado.", en: "Wealth/Inheritance should never be taxed.", effect: { axis: "eco_sys", weight: 1 } },
    { id: "en_416", langs: ["en"], pt: "[EN] Melhor pobre mas livre, que rico sob ditadura.", en: "Better to be poor but free, than rich under dictatorship.", effect: { axis: "gov_scope", weight: -1 } },
    { id: "en_417", langs: ["en"], pt: "[EN] Proibir tecnologia que substitui trabalho.", en: "We should ban technology that replaces human labor.", effect: { axis: "tech_speed", weight: -1 } },
    { id: "en_418", langs: ["en"], pt: "[EN] Moeda única global.", en: "A global single currency.", effect: { axis: "dip_align", weight: 1 } },
    { id: "en_419", langs: ["en"], pt: "[EN] Armas nucleares são justificáveis.", en: "Nuclear weapons are justifiable for survival.", effect: { axis: "phil_moral", weight: -1 } },
    { id: "en_420", langs: ["en"], pt: "[EN] Refugiados têm direito moral de entrar.", en: "Refugees have a moral right to enter wealthy countries.", effect: { axis: "dip_align", weight: 1 } },
    { id: "en_421", langs: ["en"], pt: "[EN] Preferível 10 inocentes presos que 1 culpado solto.", en: "Better 10 innocents jailed than 1 guilty free.", effect: { axis: "law_type", weight: -1 } },
    { id: "en_422", langs: ["en"], pt: "[EN] Escola deve ensinar verdade oficial da nação.", en: "School should teach official national truth.", effect: { axis: "dip_align", weight: -1 } },
    { id: "en_423", langs: ["en"], pt: "[EN] Medicina tradicional igual à moderna.", en: "Traditional medicine should have equal status to modern.", effect: { axis: "soc_time", weight: -1 } },
    { id: "en_424", langs: ["en"], pt: "[EN] Líder é sagrado.", en: "The leader should be seen as sacred.", effect: { axis: "gov_form", weight: -1 } },
    { id: "en_425", langs: ["en"], pt: "[EN] Proibir álcool e jogo.", en: "Government should ban alcohol and gambling.", effect: { axis: "gov_scope", weight: 1 } },
    { id: "en_426", langs: ["en"], pt: "[EN] País auto-suficiente em tudo.", en: "Country should be self-sufficient in everything.", effect: { axis: "dip_align", weight: -1 } },
    { id: "en_427", langs: ["en"], pt: "[EN] Pequena taxa extra (suborno) é normal.", en: "Paying a small bribe is acceptable.", effect: { axis: "dip_moral", weight: -1 } },
    { id: "en_428", langs: ["en"], pt: "[EN] Animais selvagens só servem para sustento.", en: "Wild animals only have value for human use.", effect: { axis: "tech_nature", weight: 1 } },
    { id: "en_429", langs: ["en"], pt: "[EN] Internet Nacional isolada.", en: "National Internet isolated from global.", effect: { axis: "dip_align", weight: -1 } },
    { id: "en_430", langs: ["en"], pt: "[EN] Paz mundial é impossível.", en: "World peace is impossible.", effect: { axis: "phil_moral", weight: -1 } }
];
