// Manually researched 1956–1959 batch. Source coverage is not inferred by tooling.
const sources = [
  { title: 'The Election Manifesto', author: 'Jawaharlal Nehru; edição crítica Selected Works, vol. 36', date: '1956-12-12', url: 'https://nehruarchive.in/documents/the-election-manifesto-12-december-1956-8pogn', section: 'pp. 260–273: objetivos, estados, minorias, economia, Goa e política externa' },
  { title: 'Introduction — Planning Democracy', author: 'Nikhil Menon, Cambridge University Press', date: '2022', url: 'https://www.cambridge.org/core/books/planning-democracy/introduction/CF3578EA3B3B0770E7DB3124350F1B10', section: 'introdução: Estado, democracia, planeamento e substituição de importações; texto disponível consultado' },
  { title: 'Socialism in India', author: 'Madhavan K. Palat, Cambridge University Press', date: '2022-11-03', url: 'https://www.cambridge.org/core/books/abs/cambridge-history-of-socialism/socialism-in-india/B7ECB78515BAE257E49FE2E5C6FA3617', section: 'apenas resumo académico consultado; enquadramento entre conservadorismo e comunismo' },
  { title: 'Statement on Situation in Tibet', author: 'Jawaharlal Nehru, Lok Sabha; Selected Works, vol. 48', date: '1959-04-27', url: 'https://nehruarchive.in/documents/in-the-lok-sabha-statement-on-situation-in-tibet-27-april-1959-23nq9', section: 'asilo ao Dalai Lama e refugiados; condições e segurança' },
  { title: 'Statement on Economic Policy', author: 'Jawaharlal Nehru; resolução aprovada pelo AICC', date: '1956-11-11', url: 'https://nehruarchive.in/documents/statement-on-economic-policy-11-november-1956-vl6y6', section: 'A, parágrafos 2–7: indústria, importações, planeamento e modernização agrícola' },
  { title: 'To B. Ramakrishna Rao: Analysis and Future Policy', author: 'Jawaharlal Nehru; Selected Works, vol. 50', date: '1959-07-30', url: 'https://nehruarchive.in/documents/to-b-ramakrishna-rao-analysis-and-future-policy-30-july-1959-egg9z', section: 'decisão de aplicar o artigo 356 a Kerala; crítica do precedente e restrição temporária de manifestações' },
  { title: 'Preventive Detention (Continuance) Bill, 1957', author: 'Rajya Sabha, Parlamento da Índia', date: '1957-12-20', url: 'https://rsdebate.nic.in/bitstream/123456789/571167/1/PD_19_20121957_25_p3316_p3472_4.pdf', section: 'pp. impressas 3453–3465: debate, prorrogação e aprovação do projeto (páginas PDF 69–75)' },
  { title: 'Shri Jawaharlal Nehru', author: 'Prime Minister’s Office, Índia', date: 's.d.; consulta 2026-10-07', url: 'https://www.pmindia.gov.in/en/former_pm/shri-jawaharlal-nehru/', section: 'nascimento em 1889 e mandato de 1947 a 1964; biografia oficial, não avaliação independente' },
  { title: 'Report on the Second Plan', author: 'Jawaharlal Nehru, Rajya Sabha; Selected Works, vol. 33', date: '1956-05-15', url: 'https://nehruarchive.in/documents/report-on-the-second-plan-15-may-1956-7y579q', section: 'apresentação parlamentar do plano iniciado em 1 de abril; cooperação do centro com os estados' }
];
const row = (id, value, range, confidence, refs, pt, en) => ({ id, value, range, confidence, sources: refs, pt, en });
const programme = [
  row('estrutura',70,[60,80],'média',[1,9],'Autonomia linguística e cooperação centro–estados; centralização também admitida.','Linguistic autonomy and centre–state cooperation; centralisation also accepted.'),
  row('representacao',90,[80,95],'alta',[1,2],'Socialismo por métodos democráticos e competição eleitoral.','Socialism through democratic methods and electoral competition.'),
  row('poder',30,[20,45],'média',[1,2],'Liberdade individual defendida; esta linha mede o programa, não toda a prática.','Individual freedom advocated; this row measures the programme, not all government practice.'),
  row('imigracao',30,[20,45],'média',[1,4],'Pluralidade cultural e asilo tibetano; não implica fronteiras irrestritas.','Cultural pluralism and Tibetan asylum; does not imply unrestricted borders.'),
  row('diplomacia',20,[10,35],'alta',[1,4],'Negociação e não alinhamento; não significa desarmamento absoluto.','Negotiation and non-alignment; does not mean absolute disarmament.'),
  row('intervencao',60,[40,70],'média',[1,4],'Não expansão declarada, coexistindo com reivindicações territoriais sobre Goa.','Declared non-expansion alongside territorial claims over Goa.'),
  row('economia',70,[60,80],'alta',[1,2],'Setores estratégicos públicos com indústria privada admitida.','Public strategic sectors alongside private industry.'),
  row('controle',90,[80,95],'alta',[5,9],'Coordenação pelo Segundo Plano Quinquenal.','Coordination through the Second Five-Year Plan.'),
  row('comercio',80,[65,90],'média',[2,5],'Restrição de importações não essenciais e substituição de importações.','Restrictions on non-essential imports and import substitution.'),
  row('religiao',80,[70,90],'alta',[1,3],'Laicidade com proteção de todas as crenças; não ateísmo imposto.','Secularism protecting all beliefs; not enforced atheism.'),
  row('moral',80,[70,90],'alta',[1],'Reformas dos direitos das mulheres e oposição às castas; contexto de 1956.','Women’s rights reforms and opposition to caste; assessed in the 1956 context.'),
  row('tecnologia',90,[80,95],'alta',[5,9],'Modernização industrial, científica e agrícola; não posições sobre IA atual.','Industrial, scientific and agricultural modernisation; not views on contemporary AI.')
];
const practice = programme.map(a => ({ ...a }));
practice[0] = row('estrutura',60,[45,75],'média',[1,6,9],'Estados federados, mas intervenção central no governo eleito de Kerala.','Federal states, but central intervention in Kerala’s elected government.');
practice[1] = row('representacao',80,[70,90],'média',[2,6,7],'Democracia parlamentar com oposição; destituição de Kerala limita a avaliação.','Parliamentary democracy with opposition; Kerala’s dismissal qualifies the assessment.');
practice[2] = row('poder',60,[45,70],'média',[6,7],'Detenção preventiva prorrogada e restrições a manifestações, apesar das liberdades defendidas.','Preventive detention extended and demonstrations restricted despite advocated freedoms.');
const common = {
  status: 'reviewed', period: '1956–1959', reviewed: '2026-10-07', independentReview: false, sources,
  pt: { scope: '', limits: 'Intervalos representam incerteza editorial, não intervalos estatísticos. Não extrapolar para a guerra de 1962 ou a Índia atual. Enquadramento independente: Menon e Palat (deste último, apenas o resumo). Os dados herdados não foram auditados.' },
  en: { scope: '', limits: 'Ranges represent editorial uncertainty, not statistical intervals. Do not extrapolate to the 1962 war or present-day India. Independent context: Menon and Palat (only the latter’s abstract was consulted). Inherited data have not been audited.' }
};
const review = (axes, ptScope, enScope, image) => ({ ...common, axes, pt: { ...common.pt, scope: ptScope }, en: { ...common.en, scope: enScope }, ...(image ? { image } : {}) });
const portrait = { artist: 'Harry Pot / Nationaal Archief', license: 'CC0 1.0', source: 'https://commons.wikimedia.org/wiki/File:Nehru_in_the_Netherlands,_1957.jpg', pt: 'Fotografia de 9 de julho de 1957, 1536 × 1993 px. Extração de fotografia de arquivo; apenas recorte CSS.', en: 'Photograph taken on 9 July 1957, 1536 × 1993 px. Extracted from an archival photograph; CSS crop only.' };
const flag = { artist: 'Government of India / Wikimedia Commons', license: 'Domínio público / Public domain', source: 'https://commons.wikimedia.org/wiki/File:Flag_of_India.svg', pt: 'SVG fiel ao tricolor adotado em 1947, também usado em 1956–1959. Não é uma imagem gerada por IA.', en: 'SVG depicting the tricolour adopted in 1947, also used in 1956–1959. Not an AI-generated image.' };

export default {
  id: 'lote-01', entries: [
    { kind: 'ideologies', metadata: { id: 'nehruismo', name: 'Nehruísmo', category: 'Esquerda', description: 'Orientação de Jawaharlal Nehru em 1956–1959: socialismo democrático, economia mista com planeamento, laicidade, pluralismo cultural e não alinhamento. O perfil distingue o programa político das restrições aplicadas pelo governo.', phrase: 'Quero desenvolvimento planeado numa democracia pluralista, com setores públicos estratégicos e uma política externa não alinhada.', vector: null, countryId: 'india-nehru', personalityId: 'jawaharlal-nehru', religions: [] }, translation: { id: 'nehruismo', name: 'Nehruvianism', category: 'Left', description: 'Jawaharlal Nehru’s orientation in 1956–1959: democratic socialism, a planned mixed economy, secularism, cultural pluralism and non-alignment. This profile distinguishes the political programme from restrictions imposed by the government.', phrase: 'I support planned development within a pluralist democracy, with strategic public sectors and a non-aligned foreign policy.' }, review: review(programme, 'Orientação programática de 1956–1959, documentada em textos escritos e defendidos por Nehru. Não é um retrato de toda a prática governativa.', 'Programmatic orientation in 1956–1959, documented in texts written and advocated by Nehru. Not an assessment of all government practice.') },
    { kind: 'personalities', metadata: { id: 'jawaharlal-nehru', name: 'Jawaharlal Nehru', role: 'Primeiro-ministro da Índia', category: 'politico', lifespan: '1889–1964', description: 'Primeiro primeiro-ministro da Índia independente (1947–1964). Este perfil avalia 1956–1959: planeamento, economia mista e não alinhamento, confrontados com a detenção preventiva e a intervenção no governo eleito de Kerala.', imagePath: '/personalities/portraits/jawaharlal-nehru.jpg', imageSourceName: 'Harry Pot · Nationaal Archief · CC0', imageSourceUrl: portrait.source, imageNote: portrait.pt, religions: [] }, translation: { id: 'jawaharlal-nehru', name: 'Jawaharlal Nehru', role: 'Prime Minister of India', description: 'Independent India’s first prime minister (1947–1964). This profile assesses 1956–1959: planning, a mixed economy and non-alignment, considered alongside preventive detention and intervention in Kerala’s elected government.', imageNote: portrait.en }, review: review(practice, 'Posições diretamente documentadas de Nehru e decisões do seu governo em 1956–1959. O programa de 1956 tem autoria identificada na edição crítica; o vetor não é copiado da filiação partidária.', 'Directly documented positions of Nehru and his government’s decisions in 1956–1959. The critical edition identifies him as the 1956 manifesto’s author; coordinates are not inferred from party membership.', portrait) },
    { kind: 'countries', metadata: { id: 'india-nehru', name: 'Índia — era Nehru', category: 'República parlamentar com economia planeada mista', description: 'Instituições e orientação do governo indiano em 1956–1959, durante o Segundo Plano Quinquenal. Democracia parlamentar, pluralismo e não alinhamento coexistiram com detenção preventiva e intervenção central em Kerala. Não representa a Índia atual nem as opiniões da população.', flagPath: '/countries/flags/india-nehru.png', flagKind: 'Bandeira nacional usada em 1956–1959', flagSourceName: 'Wikimedia Commons', flagSourceUrl: flag.source, flagNote: 'PNG 900 × 600 convertido do SVG original.', historical: true, period: '1956–1959', vector: null, religions: [] }, translation: { id: 'india-nehru', name: 'India — Nehru era', category: 'Parliamentary republic with a planned mixed economy', description: 'Indian institutions and government orientation in 1956–1959, during the Second Five-Year Plan. Parliamentary democracy, pluralism and non-alignment coexisted with preventive detention and central intervention in Kerala. Does not represent contemporary India or public opinion.' }, review: review(practice, 'Instituições e políticas do governo da República da Índia, 1956–1959. Mede orientação e medidas documentadas, não a sua eficácia nem a opinião de toda a população. Coincidências com Nehru decorrem da unidade de análise, não de equivalência entre pessoa e país.', 'Institutions and policies of the Republic of India’s government, 1956–1959. Measures documented orientation and actions, not policy effectiveness or the beliefs of the entire population. Overlap with Nehru follows from this scope, not equivalence between a person and a country.', flag) }
  ]
};
